# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('v1model-p4-pipeline-example', ['v1model-p4-pipeline'])
    obj.source = 'v1model-p4-pipeline-example.cc'
    obj = bld.create_ns3_program('stat4-mitigation-entropy', ['v1model-p4-pipeline'])
    obj.source = 'stat4-mitigation-entropy.cc'

